# Generated by Django 5.2.7 on 2026-01-02 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobs', '0002_jobapplication_status'),
        ('app_pages', '0012_jobpost_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, upload_to='job_cvs/')),
                ('request_type', models.CharField(choices=[('job_apply', 'Job Apply'), ('company_invite', 'Company Invite')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_requests', to='app_pages.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_jobs.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.AddConstraint(
            model_name='employmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'job_apply')), fields=('user', 'job'), name='unique_job_application'),
        ),
        migrations.AddConstraint(
            model_name='employmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'company_invite')), fields=('user', 'company'), name='unique_company_invite'),
        ),
    ]
