# Generated by Django 5.2.7 on 2025-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0005_alter_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
