# Generated by Django 5.2.7 on 2025-12-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0006_employee_leave_date_employee_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
