# Generated by Django 5.2.7 on 2025-12-08 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0009_alter_employee_joined_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 12, 8)),
            preserve_default=False,
        ),
    ]
