# Generated by Django 5.2.7 on 2025-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0010_alter_employee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeejoinrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(),
        ),
    ]
