# Generated by Django 5.2.7 on 2026-01-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0012_jobpost_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
