# Generated by Django 5.2.7 on 2026-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0014_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique company username (used in URL)', unique=True),
        ),
    ]
