# Generated by Django 5.2.7 on 2025-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_alter_customuser_options_customuser_save_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsavelead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactsavelead',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactsavelead',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsavelead',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
