# Generated by Django 5.2.7 on 2025-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
