# Generated by Django 5.2.7 on 2025-11-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0006_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20, null=True, verbose_name='Preferred Contact Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('twitter', 'Twitter (X)'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('website', 'Website / Portfolio'), ('other', 'Other')], max_length=20, null=True, verbose_name='Primary Social Media'),
        ),
    ]
