# Generated by Django 5.2.7 on 2025-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0007_clickevent_latitude_clickevent_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsavelead',
            name='post_office',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contactsavelead',
            name='thana',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
