# Generated by Django 5.2.7 on 2025-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0008_contactsavelead_post_office_contactsavelead_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsavelead',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
