# Generated by Django 5.2.7 on 2025-11-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0008_remove_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media_link',
        ),
    ]
