# Generated by Django 5.2.7 on 2025-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0009_contactsavelead_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsavelead',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
