# Generated by Django 5.2.7 on 2025-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0010_alter_contactsavelead_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsavelead',
            name='location_source',
            field=models.CharField(choices=[('GPS', 'GPS'), ('IP', 'IP')], default='IP', max_length=5),
        ),
    ]
