# Generated by Django 5.2.7 on 2025-12-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0011_contactsavelead_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsavelead',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
