# Generated by Django 5.2.7 on 2025-11-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0011_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
