# Generated by Django 5.2.7 on 2025-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0012_remove_phonenumber_profile_remove_sociallink_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yearly_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
