# Generated by Django 5.2.7 on 2025-12-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0012_contactsavelead_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsavelead',
            name='visitor',
        ),
    ]
