# Generated by Django 5.2.7 on 2025-12-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0013_remove_contactsavelead_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsavelead',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='If the visitor was logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
