# Generated by Django 5.2.7 on 2025-12-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0014_contactsavelead_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='contactsavelead',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='device_ip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='location_source',
            field=models.CharField(choices=[('GPS', 'GPS'), ('IP', 'IP')], db_index=True, default='IP', max_length=5),
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsavelead',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['profile', 'timestamp'], name='app_account_profile_39ee9d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsavelead',
            index=models.Index(fields=['profile', 'timestamp'], name='app_account_profile_6b654c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsavelead',
            index=models.Index(fields=['city'], name='app_account_city_08607f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsavelead',
            index=models.Index(fields=['country'], name='app_account_country_6f122b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsavelead',
            index=models.Index(fields=['location_source'], name='app_account_locatio_3a2d6c_idx'),
        ),
    ]
