# Generated by Django 5.2.7 on 2025-11-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0015_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='default1234', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
    ]
