# Generated by Django 5.2.7 on 2025-11-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0018_alter_customuser_options_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('elite', 'Elite')], default='starter', max_length=20),
        ),
    ]
