# Generated by Django 5.2.7 on 2025-11-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0007_alter_contact_owner_alter_contact_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('call', 'Call'), ('email', 'Email')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contacts.contact')),
            ],
        ),
    ]
