# Generated by Django 5.2.7 on 2025-11-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0009_alter_contact_owner_delete_contactcalllog'),
    ]

    operations = [
    ]
